resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/d6eda836896e8fa591fb4fff141064191d7e2a76/snapshot.yaml
compiler: ghc-8.6.5


packages:
  - cardano-explorer-db
  - cardano-explorer-node
  - cardano-explorer

ghc-options:
  cardano-explorer-db:          -Wall -Werror -fwarn-redundant-constraints
  cardano-explorer-node:        -Wall -Werror -fwarn-redundant-constraints

extra-deps:
  - binary-0.8.7.0
  - bimap-0.4.0
  - brick-0.47.1
  - config-ini-0.2.4.0
  - containers-0.5.11.0
  - data-clist-0.1.2.3
  - ekg-prometheus-adapter-0.1.0.4
  - esqueleto-3.0.0
  - generic-monoid-0.1.0.0
  - libsystemd-journal-1.4.4
  - persistent-2.10.0
  - persistent-postgresql-2.10.0
  - persistent-template-2.7.2
  - prometheus-2.1.2
  - pvss-0.2.0
  - tasty-hedgehog-1.0.0.1
  - text-zipper-0.10.1
  - time-units-1.0.0
  - word-wrap-0.4.1
  - transformers-except-0.1.1

  - git: https://github.com/input-output-hk/cardano-shell
    commit: 18906dd8c109380c4b1fa20ed35100e48135aac3

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: d6eda836896e8fa591fb4fff141064191d7e2a76
    subdirs:
      - .
      - test

  - git: http://github.com/well-typed/canonical-json
    commit: ddfe3593b80b5ceb88842bb7a6f2268df75d2c2f

  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: e22be186e0b1018260ed7c5166871f82a869b94d
    subdirs:
      - contra-tracer
      - iohk-monitoring

  - git: https://github.com/input-output-hk/cardano-node
    commit: ba7a6930437ced1f795ea4df0678b6e22a36e628
    subdirs:
      - cardano-config
      - cardano-node

  - git: https://github.com/input-output-hk/cardano-base
    commit: 0e26a4f00324100b4c34f2a9c7606ae03e94d7a2
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: db1c822f1847e40eb340152b95ab3138a10f92df
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 4e8b88224d35801ebfb782e9759c96ad18de01b5
    subdirs:
      - io-sim-classes
      - network-mux
      - ouroboros-network
      - ouroboros-consensus
      - typed-protocols
      - typed-protocols-cbor
